name: "LMG95 Power Logger"
description: "Log ZES Zimmer LMG95 power measurements to InfluxDB and/or MQTT"
version: "1.3.0"
slug: "lmgtools"
url: "https://github.com/cuveland/ha-addon-lmgtools"
init: false
services:
  - mqtt:want
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  port: 2101
  interval: 1.0
  lowpass: false
  logfile: ""
  influxdb:
    enabled: false
    host: "a0d7b954-influxdb"
    port: 8086
    database: "powerlog"
    username: ""
    password: ""
  mqtt:
    enabled: false
    topic: "lmgtools"
schema:
  host: str
  port: port
  interval: float(0.05,)
  lowpass: bool
  logfile: str?
  influxdb:
    enabled: bool
    host: str
    port: port
    database: str
    username: str?
    password: password?
  mqtt:
    enabled: bool
    topic: str
